/**
 * Responsive Styles Utility
 * Provides utilities for creating responsive styles based on screen dimensions
 */

import { StyleSheet, Dimensions } from 'react-native';
import { createResponsiveStyles, getResponsiveValue } from '../theme';

// Get screen dimensions
const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

// Check if device is in landscape mode
export const isLandscape = () => screenWidth > screenHeight;

// Get responsive dimensions
export const getResponsiveDimensions = () => ({
  width: screenWidth,
  height: screenHeight,
  isLandscape: isLandscape(),
  isTablet: screenWidth >= 768,
  isDesktop: screenWidth >= 992,
});

// Create responsive styles with orientation support
export const createOrientationStyles = (styleCreator) => {
  return (isLandscape, screenWidth) => {
    const responsiveProps = {
      isLandscape,
      screenWidth,
      screenHeight,
      isTablet: screenWidth >= 768,
      isDesktop: screenWidth >= 992,
    };
    
    return StyleSheet.create(styleCreator(responsiveProps));
  };
};

// Common responsive patterns
export const responsivePatterns = {
  // Grid columns based on screen size
  getGridColumns: (screenWidth) => {
    if (screenWidth >= 992) return 3; // Desktop
    if (screenWidth >= 768) return 2; // Tablet
    return 1; // Mobile
  },
  
  // Card width based on screen size
  getCardWidth: (screenWidth, isLandscape) => {
    if (isLandscape) {
      return screenWidth >= 992 ? '30%' : '45%';
    }
    return screenWidth >= 768 ? '45%' : '100%';
  },
  
  // Font size scaling
  getScaledFontSize: (baseSize, screenWidth) => {
    const scale = Math.min(screenWidth / 375, 1.2); // Scale based on iPhone width
    return Math.round(baseSize * scale);
  },
  
  // Padding scaling
  getScaledPadding: (basePadding, screenWidth) => {
    const scale = Math.min(screenWidth / 375, 1.1);
    return Math.round(basePadding * scale);
  },
};

// Pre-built responsive style creators
export const createHomeStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#f8fffe',
  },
  gradientBackground: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  welcomeCard: {
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
  },
  headerGradient: {
    padding: 28,
    alignItems: 'center',
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginHorizontal: 10,
  },
  quickActionsSection: {
    paddingHorizontal: 20,
    marginTop: 32,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2E7D32',
    marginBottom: 20,
    textAlign: 'center',
  },
  quickActionsContainer: {
    flexDirection: isLandscape ? 'row' : 'column',
    flexWrap: isLandscape ? 'wrap' : 'nowrap',
    justifyContent: isLandscape ? 'space-around' : 'center',
    gap: isLandscape ? 16 : 20,
  },
  quickActionCard: {
    flex: isLandscape ? 1 : undefined,
    width: isLandscape ? '45%' : '100%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    minHeight: isLandscape ? 100 : 120,
    alignItems: 'center',
  },
  quickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  quickActionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2E7D32',
    marginBottom: 4,
    textAlign: 'center',
  },
  consumerDashboardSection: {
    paddingHorizontal: 20,
    marginTop: 32,
  },
  roleQuickActionsContainer: {
    flexDirection: isLandscape ? 'row' : 'column',
    flexWrap: isLandscape ? 'wrap' : 'nowrap',
    justifyContent: isLandscape ? 'space-around' : 'center',
    gap: isLandscape ? 16 : 20,
    marginBottom: 24,
  },
  roleQuickActionCard: {
    flex: isLandscape ? 1 : undefined,
    width: isLandscape ? '45%' : '100%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    minHeight: isLandscape ? 100 : 120,
    alignItems: 'center',
  },
  roleQuickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  roleQuickActionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2E7D32',
    marginBottom: 4,
    textAlign: 'center',
  },
  recentActivityContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  recentActivityTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2E7D32',
    marginBottom: 16,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  activityIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityContent: {
    flex: 1,
  },
  activityText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 2,
  },
  activityTime: {
    fontSize: 12,
    color: '#666',
  },
  noActivityContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  noActivityText: {
    fontSize: 16,
    color: '#666',
    marginTop: 12,
    marginBottom: 4,
  },
  noActivitySubtext: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
  },
  featuresSection: {
    paddingHorizontal: 20,
    marginTop: 32,
  },
  sectionTitleMain: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2E7D32',
    marginBottom: 20,
    textAlign: 'center',
  },
  featuresGrid: {
    flexDirection: isLandscape ? 'row' : 'column',
    flexWrap: isLandscape ? 'wrap' : 'nowrap',
    justifyContent: isLandscape ? 'space-around' : 'center',
    gap: isLandscape ? 16 : 20,
  },
  featureCard: {
    width: isLandscape ? (screenWidth >= 992 ? '30%' : '45%') : '100%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    minHeight: isLandscape ? 120 : 140,
    alignItems: 'center',
  },
  comingSoonCard: {
    opacity: 0.7,
  },
  featureIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2E7D32',
    marginBottom: 8,
    textAlign: 'center',
  },
  featureDescription: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 16,
  },
  featureButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  featureButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    gap: 8,
  },
  featureButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  comingSoonButton: {
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  comingSoonText: {
    color: '#666',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
}));

export const createStatsStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#f8fffe',
  },
  gradient: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 24,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  statsContainer: {
    flexDirection: isLandscape ? 'row' : 'column',
    flexWrap: isLandscape ? 'wrap' : 'nowrap',
    justifyContent: isLandscape ? 'space-around' : 'center',
    gap: isLandscape ? 16 : 20,
    paddingHorizontal: 20,
  },
  statItem: {
    width: responsivePatterns.getCardWidth(screenWidth, isLandscape),
    minHeight: isLandscape ? 120 : 140,
  },
}));

export const createProfileStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#F8FFFE',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 24,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  statsContainer: {
    flexDirection: isLandscape ? 'row' : 'column',
    flexWrap: isLandscape ? 'wrap' : 'nowrap',
    justifyContent: isLandscape ? 'space-around' : 'center',
    gap: isLandscape ? 16 : 20,
    paddingHorizontal: 20,
  },
  statItem: {
    width: responsivePatterns.getCardWidth(screenWidth, isLandscape),
    minHeight: isLandscape ? 120 : 140,
  },
  modalContent: {
    width: isLandscape ? '60%' : '90%',
    maxHeight: isLandscape ? '70%' : '80%',
    padding: isLandscape ? 24 : 20,
  },
}));

export const createCropsStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#f8fffe',
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerSection: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 24,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  headerGradient: {
    padding: isLandscape ? 20 : 24,
    alignItems: 'center',
  },
  headerContent: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: isLandscape ? 20 : 24,
    fontWeight: '800',
    color: '#fff',
    marginTop: 12,
    marginBottom: 8,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: isLandscape ? 12 : 14,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 20,
  },
  formContainer: {
    paddingHorizontal: 20,
    gap: 20,
  },
  inputRow: {
    flexDirection: isLandscape ? 'row' : 'column',
    gap: isLandscape ? 16 : 20,
  },
  inputHalf: {
    flex: isLandscape ? 1 : undefined,
    width: isLandscape ? '48%' : '100%',
  },
  buttonRow: {
    flexDirection: isLandscape ? 'row' : 'column',
    gap: isLandscape ? 16 : 20,
    marginTop: 20,
  },
  buttonHalf: {
    flex: isLandscape ? 1 : undefined,
    width: isLandscape ? '48%' : '100%',
  },
  cameraContainer: {
    height: isLandscape ? 200 : 250,
    marginBottom: 20,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  cameraView: {
    flex: 1,
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  removeImageButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
    padding: 8,
  },
  submitButton: {
    borderRadius: 16,
    overflow: 'hidden',
    marginTop: 20,
  },
  submitButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  formTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2E7D32',
    marginBottom: 20,
    textAlign: 'center',
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2E7D32',
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#fff',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    backgroundColor: '#fff',
  },
  picker: {
    height: 50,
  },
  imageSection: {
    marginBottom: 20,
  },
  imageSubtext: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
  },
  imageButtons: {
    flexDirection: isLandscape ? 'row' : 'column',
    gap: 12,
    marginBottom: 16,
  },
  imageButton: {
    flex: isLandscape ? 1 : undefined,
    backgroundColor: '#f0f9f1',
    borderWidth: 2,
    borderColor: '#49A760',
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 60,
  },
  imageButtonText: {
    color: '#49A760',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },
  imagePreview: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: 12,
  },
  previewImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  submitGradient: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  cameraHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 1,
  },
  cameraCloseButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    padding: 8,
  },
  cameraTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  camera: {
    flex: 1,
  },
  cameraControls: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 20,
    alignItems: 'center',
    zIndex: 1,
  },
  captureButton: {
    backgroundColor: '#49A760',
    borderRadius: 40,
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
}));

export const createStatsStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#f8fffe',
  },
  gradient: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 24,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  headerGradient: {
    padding: 24,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
    marginTop: 12,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginBottom: 24,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'hidden',
  },
  sectionHeader: {
    marginBottom: 20,
  },
  sectionHeaderGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#fff',
    marginLeft: 12,
  },
  selectorContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  selectorLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F4E3D',
    marginBottom: 12,
  },
  pickerContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
    overflow: 'hidden',
  },
  selectedCropDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  cropIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  selectedCropText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F4E3D',
    flex: 1,
  },
  picker: {
    height: 50,
    color: '#1F4E3D',
  },
  pickerItem: {
    fontSize: 14,
  },
  chartWrapper: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
    gap: 8,
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#49A760',
  },
  chartStats: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: '#666',
    fontWeight: '500',
  },
  chartScrollContainer: {
    paddingRight: 20,
  },
  chartContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: isLandscape ? 20 : 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    minHeight: isLandscape ? 320 : 280,
  },
  xAxisLabel: {
    color: '#666',
    fontSize: 11,
    fontWeight: '500',
  },
  yAxisLabel: {
    color: '#666',
    fontSize: 12,
    fontWeight: '500',
  },
  noDataContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    marginHorizontal: 20,
  },
  noDataText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginTop: 16,
    textAlign: 'center',
  },
  noDataSubtext: {
    fontSize: 12,
    color: '#999',
    marginTop: 8,
    textAlign: 'center',
  },
  marketAnalyticsContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  marketAnalyticsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F4E3D',
    textAlign: 'center',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  primaryStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: isLandscape ? 16 : 12,
    flexWrap: isLandscape ? 'nowrap' : 'wrap',
  },
  primaryStatItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e9ecef',
    minHeight: 80,
  },
  primaryStatValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F4E3D',
    marginTop: 8,
    marginBottom: 4,
  },
  primaryStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#666',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  secondaryStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: isLandscape ? 12 : 8,
    flexWrap: isLandscape ? 'nowrap' : 'wrap',
  },
  secondaryStatItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e9ecef',
    minHeight: 60,
  },
  secondaryStatValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F4E3D',
    marginTop: 6,
    marginBottom: 2,
  },
  secondaryStatLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#666',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  todayPricesSection: {
    backgroundColor: '#f0f9ff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#49A760',
    borderStyle: 'dashed',
  },
  todayPricesTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#49A760',
    textAlign: 'center',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  todayPricesRow: {
    flexDirection: isLandscape ? 'row' : 'row',
    justifyContent: 'space-between',
    gap: isLandscape ? 20 : 16,
    flexWrap: isLandscape ? 'nowrap' : 'wrap',
  },
  todayPriceItem: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  todayPriceValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1F4E3D',
    marginTop: 8,
    marginBottom: 4,
  },
  todayPriceLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#49A760',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  todayPriceCount: {
    fontSize: 9,
    color: '#666',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  todayAverageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    gap: 8,
  },
  todayAverageText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FF9800',
    textAlign: 'center',
  },
  overallStatsTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F4E3D',
    textAlign: 'center',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
}));

export const createProfileStyles = createOrientationStyles(({ isLandscape, screenWidth }) => ({
  container: {
    flex: 1,
    backgroundColor: '#f8fffe',
  },
  gradientBackground: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerSection: {
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  avatarContainer: {
    marginBottom: 20,
  },
  avatarGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  avatarText: {
    fontSize: 40,
    color: '#fff',
    fontWeight: '700',
    letterSpacing: 1,
  },
  userName: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 4,
    textAlign: 'center',
  },
  userRole: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  profileCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F4E3D',
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#666',
    fontWeight: '400',
  },
  editButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#49A760',
    borderRadius: 20,
  },
  editButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  fieldsContainer: {
    padding: 24,
  },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  fieldIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f8fffe',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  iconText: {
    fontSize: 20,
  },
  fieldContent: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
    marginBottom: 4,
  },
  fieldValue: {
    fontSize: 16,
    color: '#1F4E3D',
    fontWeight: '600',
  },
  actionsContainer: {
    paddingHorizontal: 20,
    paddingTop: 30,
    gap: 16,
  },
  secondaryButton: {
    backgroundColor: '#fff',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#49A760',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  secondaryButtonText: {
    color: '#49A760',
    fontSize: 16,
    fontWeight: '600',
  },
  logoutButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  logoutGradient: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fffe',
    paddingHorizontal: 20,
  },
  errorCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    width: '100%',
    maxWidth: 320,
  },
  errorIcon: {
    fontSize: 60,
    marginBottom: 20,
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 12,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  loginButton: {
    backgroundColor: '#49A760',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 18,
    color: '#666',
    marginTop: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: isLandscape ? '80%' : '90%',
    maxHeight: isLandscape ? '80%' : '70%',
    padding: isLandscape ? 24 : 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
  },
  modalList: {
    maxHeight: 300,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 4,
  },
  selectedModalItem: {
    backgroundColor: '#e8f5e8',
  },
  modalItemFlag: {
    fontSize: 20,
    marginRight: 12,
  },
  modalItemIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  modalItemContent: {
    flex: 1,
  },
  modalItemText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  selectedModalItemText: {
    color: '#49A760',
    fontWeight: '600',
  },
  modalItemDescription: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  toggleSwitch: {
    width: 44,
    height: 24,
    borderRadius: 12,
    padding: 2,
    justifyContent: 'center',
  },
  toggleCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  comingSoonText: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
  },
  statsContainer: {
    flexDirection: isLandscape ? 'row' : 'row',
    flexWrap: isLandscape ? 'nowrap' : 'wrap',
    justifyContent: isLandscape ? 'space-around' : 'space-between',
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: isLandscape ? 20 : 16,
  },
  statItem: {
    alignItems: 'center',
    width: isLandscape ? '22%' : '45%',
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f0f9f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
    textAlign: 'center',
  },
  bottomSheetStyle: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
  },
  aboutSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
    marginTop: 20,
  },
  aboutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  aboutButtonText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1F4E3D',
    marginLeft: 12,
  },
  settingsSection: {
    marginBottom: 24,
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 4,
  },
  settingIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f9f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  settingContent: {
    flex: 1,
  },
  settingLabel: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
    marginBottom: 2,
  },
  settingDescription: {
    fontSize: 14,
    color: '#666',
  },
  aboutContent: {
    padding: 20,
    alignItems: 'center',
  },
  aboutLogo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#f0f9f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  aboutLogoText: {
    fontSize: 40,
  },
  aboutTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1F4E3D',
    marginBottom: 8,
  },
  aboutSubtitle: {
    fontSize: 18,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
  },
  aboutDescription: {
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 24,
  },
  aboutFeatures: {
    alignSelf: 'stretch',
    marginBottom: 24,
  },
  aboutFeaturesTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F4E3D',
    marginBottom: 12,
  },
  aboutFeature: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 6,
  },
  aboutProject: {
    alignSelf: 'stretch',
    marginBottom: 24,
  },
  aboutProjectTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F4E3D',
    marginBottom: 12,
  },
  aboutProjectText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 6,
    textAlign: 'center',
  },
  aboutVersion: {
    fontSize: 14,
    color: '#999',
    fontStyle: 'italic',
  },
}));

export default {
  isLandscape,
  getResponsiveDimensions,
  createOrientationStyles,
  responsivePatterns,
  createHomeStyles,
  createStatsStyles,
  createProfileStyles,
  createCropsStyles,
};
