import { StyleSheet, Dimensions } from "react-native";
import { MAP_CONFIG } from "@/constants/mapConfig";

const { width } = Dimensions.get("window");

export const mapStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eafbe7",
  },
  header: {
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: MAP_CONFIG.COLORS.SECONDARY,
  },
  headerControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  cropSelectorContainer: {
    alignItems: "flex-end",
  },
  cropSelectorLabel: {
    fontSize: 12,
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 4,
  },
  cropSelectorButton: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  cropSelectorButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  mapTypeSelector: {
    flexDirection: "row",
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    padding: 2,
  },
  mapTypeButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: "center",
  },
  selectedMapTypeButton: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
  },
  mapTypeText: {
    fontSize: 14,
    color: MAP_CONFIG.COLORS.SECONDARY,
    fontWeight: "500",
  },
  selectedMapTypeText: {
    color: "#fff",
  },
  contentScroll: {
    flex: 1,
  },
  mapContainer: {
    height: 400,
    backgroundColor: "#e0e0e0",
  },
  map: {
    flex: 1,
  },
  mapLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
  },
  mapLoadingText: {
    fontSize: 16,
    color: MAP_CONFIG.COLORS.SECONDARY,
  },
  sliderSection: {
    backgroundColor: "#fff",
    padding: 16,
    marginTop: 1,
    position: "relative",
  },
  sliderLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 12,
    textAlign: "center",
  },
  slider: {
    width: "100%",
    height: 40,
    marginBottom: 20,
  },
  sliderThumb: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
    width: 20,
    height: 20,
  },
  sliderRangeLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 30,
  },
  sliderRangeLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  sliderRangeLabelCenter: {
    textAlign: "center",
  },
  sliderMarkersContainer: {
    position: "relative",
    height: 30,
  },
  sliderCurrentIndicator: {
    position: "absolute",
    alignItems: "center",
    transform: [{ translateX: -1 }],
  },
  sliderCurrentIndicatorLine: {
    width: 2,
    height: 15,
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
  },
  sliderCurrentIndicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
    marginTop: 2,
  },
  sliderMarker: {
    position: "absolute",
    alignItems: "center",
    transform: [{ translateX: -1 }],
  },
  sliderMarkerLine: {
    width: 1,
    height: 8,
    backgroundColor: "#ccc",
  },
  sliderMarkerText: {
    fontSize: 10,
    color: "#666",
    marginTop: 2,
  },
  sliderMinorMarker: {
    position: "absolute",
    alignItems: "center",
    transform: [{ translateX: -0.5 }],
  },
  sliderMinorMarkerLine: {
    width: 1,
    height: 4,
    backgroundColor: "#ddd",
  },
  consumerInfoPanel: {
    backgroundColor: "#fff",
    padding: 20,
    marginTop: 1,
  },
  consumerInfoHeaderCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fffe",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: MAP_CONFIG.COLORS.PRIMARY,
  },
  cropIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cropIcon: {
    fontSize: 24,
  },
  cropInfoContainer: {
    flex: 1,
  },
  consumerInfoTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 4,
  },
  consumerInfoSubtitle: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  consumerStatsGrid: {
    flexDirection: "row",
    gap: 16,
  },
  consumerStatCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f0f0f0",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  statIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f8fffe",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  statIcon: {
    fontSize: 20,
  },
  consumerStatLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 8,
    textAlign: "center",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "center",
  },
  currencySymbol: {
    fontSize: 16,
    fontWeight: "600",
    color: MAP_CONFIG.COLORS.PRIMARY,
    marginRight: 2,
  },
  consumerStatValue: {
    fontSize: 24,
    fontWeight: "800",
    color: MAP_CONFIG.COLORS.PRIMARY,
  },
  consumerStatUnit: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666",
    marginLeft: 2,
  },
  consumerStatSubtext: {
    fontSize: 11,
    color: "#999",
    marginTop: 4,
    textAlign: "center",
  },
  priceUnitContainer: {
    flexDirection: "row",
    backgroundColor: "#fff",
    padding: 16,
    marginTop: 1,
    gap: 8,
  },
  priceUnitButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MAP_CONFIG.COLORS.PRIMARY,
    alignItems: "center",
  },
  priceUnitButtonActive: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
  },
  priceUnitText: {
    fontSize: 14,
    fontWeight: "600",
    color: MAP_CONFIG.COLORS.PRIMARY,
  },
  priceUnitTextActive: {
    color: "#fff",
  },
  mapLegend: {
    backgroundColor: "#fff",
    padding: 16,
    marginTop: 1,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 12,
  },
  legendItems: {
    gap: 8,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  legendMarker: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#fff",
  },
  legendMarkerCenter: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: MAP_CONFIG.COLORS.USER_LOCATION,
    borderWidth: 2,
    borderColor: "#fff",
  },
  legendText: {
    fontSize: 14,
    color: MAP_CONFIG.COLORS.SECONDARY,
  },
  // Modern Legend Styles
  modernMapLegend: {
    backgroundColor: "#fff",
    marginTop: 10,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  legendHeader: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  legendTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendCropIcon: {
    fontSize: 28,
    marginRight: 12,
  },
  legendTitleTextContainer: {
    flex: 1,
  },
  legendTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 2,
  },
  legendSubtitle: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  legendItemsContainer: {
    padding: 20,
    gap: 16,
  },
  modernLegendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  legendMarkerContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f8f9fa",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  modernLegendMarker: {
    width: 16,
    height: 16,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  modernLegendMarkerCenter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  legendTextContainer: {
    flex: 1,
  },
  modernLegendLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 2,
  },
  modernLegendDescription: {
    fontSize: 13,
    color: "#666",
    fontWeight: "400",
  },
  debugSection: {
    backgroundColor: "#f9f9f9",
    padding: 12,
    marginTop: 1,
  },
  debugText: {
    fontSize: 12,
    color: "#666",
    marginBottom: 2,
  },
  testButton: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
    alignItems: "center",
  },
  testButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  chartSection: {
    backgroundColor: "#fff",
    padding: 16,
    marginTop: 8,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: MAP_CONFIG.COLORS.SECONDARY,
    marginBottom: 4,
  },
  chartSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 16,
  },
  chartScroll: {
    marginHorizontal: -16,
  },
  chartScrollContent: {
    paddingHorizontal: 16,
  },
  chartWrapper: {
    alignItems: "center",
  },
  // No Data Message Styles
  noDataCard: {
    backgroundColor: "#fff3cd",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#ffeaa7",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  noDataIconContainer: {
    alignItems: "center",
    marginBottom: 12,
  },
  noDataIcon: {
    fontSize: 32,
  },
  noDataContent: {
    alignItems: "center",
  },
  noDataTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#856404",
    textAlign: "center",
    marginBottom: 8,
  },
  noDataSubtitle: {
    fontSize: 14,
    color: "#856404",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  increaseRadiusButton: {
    backgroundColor: MAP_CONFIG.COLORS.PRIMARY,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  increaseRadiusButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  
  // Price Display Section
  priceDisplaySection: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  priceSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F4E3D",
    marginBottom: 12,
    textAlign: "center",
  },
  dateRangeSelector: {
    flexDirection: "row",
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 3,
    marginBottom: 16,
  },
  dateButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  dateButtonActive: {
    backgroundColor: "#49A760",
  },
  dateButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  dateButtonTextActive: {
    color: "#fff",
  },
  priceCardsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  priceCard: {
    flex: 1,
    backgroundColor: "#f8fffe",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e8f5e8",
  },
  priceCardTitle: {
    fontSize: 11,
    fontWeight: "600",
    color: "#666",
    marginBottom: 6,
    textAlign: "center",
  },
  priceCardValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#49A760",
    textAlign: "center",
  },
  noDataMessage: {
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  noDataText: {
    fontSize: 14,
    color: "#6c757d",
    textAlign: "center",
    lineHeight: 20,
  },
  
  // Collapsed state styles for price section
  priceDisplaySectionCollapsed: {
    padding: 12,
    marginBottom: 12,
    transform: [{ scaleY: 0.85 }],
  },
  priceSectionTitleCollapsed: {
    fontSize: 14,
    marginBottom: 8,
  },
  dateRangeSelectorCollapsed: {
    padding: 2,
    marginBottom: 12,
  },
  dateButtonCollapsed: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  dateButtonTextCollapsed: {
    fontSize: 12,
  },
  priceCardsContainerCollapsed: {
    gap: 8,
  },
  priceCardCollapsed: {
    padding: 10,
  },
  priceCardTitleCollapsed: {
    fontSize: 10,
    marginBottom: 4,
  },
  priceCardValueCollapsed: {
    fontSize: 14,
  },
  
  // Enhanced Radius Section
  radiusSection: {
    backgroundColor: "#fff",
    padding: 20,
    marginTop: 1,
    marginHorizontal: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  radiusSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F4E3D",
    marginBottom: 8,
    textAlign: "center",
  },
  radiusSectionSubtitle: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 16,
  },
  radiusTypeToggle: {
    flexDirection: "row",
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  radiusTypeButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  radiusTypeButtonActive: {
    backgroundColor: "#49A760",
  },
  radiusTypeButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  radiusTypeButtonTextActive: {
    color: "#fff",
  },
  radiusSliderContainer: {
    alignItems: "center",
  },
  radiusValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#49A760",
    marginBottom: 16,
  },
  sliderContainer: {
    width: "100%",
    marginBottom: 20,
  },
  sliderHint: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginBottom: 12,
    fontStyle: "italic",
  },
  sliderTrack: {
    height: 6,
    backgroundColor: "#e0e0e0",
    borderRadius: 3,
    marginBottom: 16,
    position: "relative",
  },
  sliderFill: {
    height: "100%",
    backgroundColor: "#49A760",
    borderRadius: 3,
  },
  sliderThumb: {
    position: "absolute",
    width: 20,
    height: 20,
    backgroundColor: "#49A760",
    borderRadius: 10,
    borderWidth: 3,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    top: -7, // Center the thumb on the track
    transform: [{ translateX: -10 }], // Center horizontally
  },
  sliderSteps: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
  },
  sliderStep: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  sliderStepActive: {
    backgroundColor: "#49A760",
    borderColor: "#49A760",
  },
  sliderStepText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#666",
  },
  sliderStepTextActive: {
    color: "#fff",
  },
  kmSliderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  kmButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#f8f9fa",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    minWidth: 60,
    alignItems: "center",
  },
  kmButtonActive: {
    backgroundColor: "#49A760",
    borderColor: "#49A760",
  },
  kmButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  kmButtonTextActive: {
    color: "#fff",
  },
  
  // Date Picker Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    width: "90%",
    maxWidth: 400,
    padding: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#333",
  },
  datePickerContainer: {
    gap: 20,
  },
  datePickerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  datePickerLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    gap: 8,
  },
  datePickerButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  applyDateButton: {
    backgroundColor: "#49A760",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  applyDateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  applyDateButtonDisabled: {
    backgroundColor: "#ccc",
  },
  applyDateButtonTextDisabled: {
    color: "#666",
  },
});
