import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");
export const marketsyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fffe",
    },
    gradientBackground: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    headerSection: {
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    headerGradient: {
        borderRadius: 24,
        padding: 28,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 10,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: "800",
        color: "#fff",
        textAlign: "center",
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    headerSubtitle: {
        fontSize: 16,
        color: "rgba(255, 255, 255, 0.9)",
        textAlign: "center",
        lineHeight: 22,
    },
    periodSelectionSection: {
        paddingTop: 24,
        paddingHorizontal: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#1F4E3D",
        marginBottom: 16,
    },
    periodButtonsContainer: {
        flexDirection: "row",
        gap: 12,
    },
    periodButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: "#fff",
        borderRadius: 12,
        borderWidth: 2,
        borderColor: "#e9ecef",
        gap: 8,
    },
    periodButtonActive: {
        backgroundColor: "#49A760",
        borderColor: "#49A760",
    },
    periodButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#49A760",
    },
    periodButtonTextActive: {
        color: "#fff",
    },
    marketOverviewSection: {
        paddingTop: 24,
        paddingHorizontal: 20,
    },
    marketOverviewCard: {
        backgroundColor: "#fff",
        borderRadius: 20,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
    },
    overviewHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    overviewTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#fff",
    },
    overviewStats: {
        padding: 20,
    },
    overviewStatRow: {
        flexDirection: "row",
        gap: 20,
    },
    overviewStatItem: {
        flex: 1,
        alignItems: "center",
    },
    overviewStatLabel: {
        fontSize: 12,
        fontWeight: "600",
        color: "#666",
        marginBottom: 4,
        textTransform: "uppercase",
    },
    overviewStatValue: {
        fontSize: 24,
        fontWeight: "700",
        color: "#1F4E3D",
    },
    priceStatsSection: {
        paddingTop: 24,
        paddingHorizontal: 20,
    },
    priceStatsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 16,
    },
    priceStatCard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        width: (width - 56) / 2,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        minHeight: 120,
    },
    priceStatHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 12,
    },
    priceStatLabel: {
        fontSize: 12,
        fontWeight: "600",
        color: "#666",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    priceStatValue: {
        fontSize: 24,
        fontWeight: "700",
        color: "#1F4E3D",
        marginBottom: 8,
    },
    priceChangeIndicator: {
        fontSize: 20,
        fontWeight: "600",
    },
    detailedBreakdownSection: {
        paddingTop: 24,
        paddingHorizontal: 20,
    },
    breakdownCard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    breakdownRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    breakdownLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: "#666",
    },
    breakdownValue: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1F4E3D",
    },
    loadingContainer: {
        alignItems: "center",
        paddingVertical: 40,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: "#666",
        textAlign: "center",
    },
    unauthorizedContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 40,
    },
    unauthorizedText: {
        fontSize: 18,
        color: "#666",
        textAlign: "center",
        marginTop: 16,
    },
});
